/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressAddDTO
 */
export interface AddressAddDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    county?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    street?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressAddDTO
     */
    number?: number;
}

/**
 * Check if a given object implements the AddressAddDTO interface.
 */
export function instanceOfAddressAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressAddDTOFromJSON(json: any): AddressAddDTO {
    return AddressAddDTOFromJSONTyped(json, false);
}

export function AddressAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'county': !exists(json, 'county') ? undefined : json['county'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function AddressAddDTOToJSON(value?: AddressAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'county': value.county,
        'city': value.city,
        'street': value.street,
        'number': value.number,
    };
}

