/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BuildingAddDTO } from './BuildingAddDTO';
import {
    BuildingAddDTOFromJSON,
    BuildingAddDTOFromJSONTyped,
    BuildingAddDTOToJSON,
} from './BuildingAddDTO';

/**
 * 
 * @export
 * @interface AnnouncementAddDTO
 */
export interface AnnouncementAddDTO {
    /**
     * 
     * @type {string}
     * @memberof AnnouncementAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementAddDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AnnouncementAddDTO
     */
    price?: number;
    /**
     * 
     * @type {BuildingAddDTO}
     * @memberof AnnouncementAddDTO
     */
    building?: BuildingAddDTO;
}

/**
 * Check if a given object implements the AnnouncementAddDTO interface.
 */
export function instanceOfAnnouncementAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnnouncementAddDTOFromJSON(json: any): AnnouncementAddDTO {
    return AnnouncementAddDTOFromJSONTyped(json, false);
}

export function AnnouncementAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'building': !exists(json, 'building') ? undefined : BuildingAddDTOFromJSON(json['building']),
    };
}

export function AnnouncementAddDTOToJSON(value?: AnnouncementAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'price': value.price,
        'building': BuildingAddDTOToJSON(value.building),
    };
}

