/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnnouncementDTO } from './AnnouncementDTO';
import {
    AnnouncementDTOFromJSON,
    AnnouncementDTOFromJSONTyped,
    AnnouncementDTOToJSON,
} from './AnnouncementDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AnnouncementDTORequestResponse
 */
export interface AnnouncementDTORequestResponse {
    /**
     * 
     * @type {AnnouncementDTO}
     * @memberof AnnouncementDTORequestResponse
     */
    response?: AnnouncementDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AnnouncementDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AnnouncementDTORequestResponse interface.
 */
export function instanceOfAnnouncementDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnnouncementDTORequestResponseFromJSON(json: any): AnnouncementDTORequestResponse {
    return AnnouncementDTORequestResponseFromJSONTyped(json, false);
}

export function AnnouncementDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AnnouncementDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AnnouncementDTORequestResponseToJSON(value?: AnnouncementDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AnnouncementDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

