/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnouncementUpdateDTO
 */
export interface AnnouncementUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AnnouncementUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AnnouncementUpdateDTO
     */
    price?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AnnouncementUpdateDTO
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the AnnouncementUpdateDTO interface.
 */
export function instanceOfAnnouncementUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnnouncementUpdateDTOFromJSON(json: any): AnnouncementUpdateDTO {
    return AnnouncementUpdateDTOFromJSONTyped(json, false);
}

export function AnnouncementUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function AnnouncementUpdateDTOToJSON(value?: AnnouncementUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'price': value.price,
        'isActive': value.isActive,
    };
}

