/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BuildingDTO } from './BuildingDTO';
import {
    BuildingDTOFromJSON,
    BuildingDTOFromJSONTyped,
    BuildingDTOToJSON,
} from './BuildingDTO';

/**
 * 
 * @export
 * @interface AnnouncementDTO
 */
export interface AnnouncementDTO {
    /**
     * 
     * @type {string}
     * @memberof AnnouncementDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AnnouncementDTO
     */
    price?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AnnouncementDTO
     */
    isActive?: boolean;
    /**
     * 
     * @type {BuildingDTO}
     * @memberof AnnouncementDTO
     */
    building?: BuildingDTO;
}

/**
 * Check if a given object implements the AnnouncementDTO interface.
 */
export function instanceOfAnnouncementDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnnouncementDTOFromJSON(json: any): AnnouncementDTO {
    return AnnouncementDTOFromJSONTyped(json, false);
}

export function AnnouncementDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'building': !exists(json, 'building') ? undefined : BuildingDTOFromJSON(json['building']),
    };
}

export function AnnouncementDTOToJSON(value?: AnnouncementDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'title': value.title,
        'description': value.description,
        'price': value.price,
        'isActive': value.isActive,
        'building': BuildingDTOToJSON(value.building),
    };
}

