/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnnouncementDTOPagedResponse } from './AnnouncementDTOPagedResponse';
import {
    AnnouncementDTOPagedResponseFromJSON,
    AnnouncementDTOPagedResponseFromJSONTyped,
    AnnouncementDTOPagedResponseToJSON,
} from './AnnouncementDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AnnouncementDTOPagedResponseRequestResponse
 */
export interface AnnouncementDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {AnnouncementDTOPagedResponse}
     * @memberof AnnouncementDTOPagedResponseRequestResponse
     */
    response?: AnnouncementDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AnnouncementDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AnnouncementDTOPagedResponseRequestResponse interface.
 */
export function instanceOfAnnouncementDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnnouncementDTOPagedResponseRequestResponseFromJSON(json: any): AnnouncementDTOPagedResponseRequestResponse {
    return AnnouncementDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function AnnouncementDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AnnouncementDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AnnouncementDTOPagedResponseRequestResponseToJSON(value?: AnnouncementDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AnnouncementDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

