/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressAddDTO } from './AddressAddDTO';
import {
    AddressAddDTOFromJSON,
    AddressAddDTOFromJSONTyped,
    AddressAddDTOToJSON,
} from './AddressAddDTO';

/**
 * 
 * @export
 * @interface BuildingAddDTO
 */
export interface BuildingAddDTO {
    /**
     * 
     * @type {number}
     * @memberof BuildingAddDTO
     */
    surface?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingAddDTO
     */
    roomsNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingAddDTO
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof BuildingAddDTO
     */
    specificCharacteristics?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BuildingAddDTO
     */
    floor?: number | null;
    /**
     * 
     * @type {AddressAddDTO}
     * @memberof BuildingAddDTO
     */
    address?: AddressAddDTO;
}

/**
 * Check if a given object implements the BuildingAddDTO interface.
 */
export function instanceOfBuildingAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BuildingAddDTOFromJSON(json: any): BuildingAddDTO {
    return BuildingAddDTOFromJSONTyped(json, false);
}

export function BuildingAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'surface': !exists(json, 'surface') ? undefined : json['surface'],
        'roomsNumber': !exists(json, 'roomsNumber') ? undefined : json['roomsNumber'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'specificCharacteristics': !exists(json, 'specificCharacteristics') ? undefined : json['specificCharacteristics'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'address': !exists(json, 'address') ? undefined : AddressAddDTOFromJSON(json['address']),
    };
}

export function BuildingAddDTOToJSON(value?: BuildingAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'surface': value.surface,
        'roomsNumber': value.roomsNumber,
        'year': value.year,
        'specificCharacteristics': value.specificCharacteristics,
        'floor': value.floor,
        'address': AddressAddDTOToJSON(value.address),
    };
}

