/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BuildingDTO } from './BuildingDTO';
import {
    BuildingDTOFromJSON,
    BuildingDTOFromJSONTyped,
    BuildingDTOToJSON,
} from './BuildingDTO';

/**
 * 
 * @export
 * @interface BuildingDTOPagedResponse
 */
export interface BuildingDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BuildingDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<BuildingDTO>}
     * @memberof BuildingDTOPagedResponse
     */
    data?: Array<BuildingDTO> | null;
}

/**
 * Check if a given object implements the BuildingDTOPagedResponse interface.
 */
export function instanceOfBuildingDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BuildingDTOPagedResponseFromJSON(json: any): BuildingDTOPagedResponse {
    return BuildingDTOPagedResponseFromJSONTyped(json, false);
}

export function BuildingDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(BuildingDTOFromJSON)),
    };
}

export function BuildingDTOPagedResponseToJSON(value?: BuildingDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(BuildingDTOToJSON)),
    };
}

