/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuildingUpdateDTO
 */
export interface BuildingUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof BuildingUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BuildingUpdateDTO
     */
    surface?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingUpdateDTO
     */
    roomsNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingUpdateDTO
     */
    year?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingUpdateDTO
     */
    specificCharacteristics?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BuildingUpdateDTO
     */
    floor?: number | null;
}

/**
 * Check if a given object implements the BuildingUpdateDTO interface.
 */
export function instanceOfBuildingUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BuildingUpdateDTOFromJSON(json: any): BuildingUpdateDTO {
    return BuildingUpdateDTOFromJSONTyped(json, false);
}

export function BuildingUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'surface': !exists(json, 'surface') ? undefined : json['surface'],
        'roomsNumber': !exists(json, 'roomsNumber') ? undefined : json['roomsNumber'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'specificCharacteristics': !exists(json, 'specificCharacteristics') ? undefined : json['specificCharacteristics'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
    };
}

export function BuildingUpdateDTOToJSON(value?: BuildingUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'surface': value.surface,
        'roomsNumber': value.roomsNumber,
        'year': value.year,
        'specificCharacteristics': value.specificCharacteristics,
        'floor': value.floor,
    };
}

