/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface BuildingDTO
 */
export interface BuildingDTO {
    /**
     * 
     * @type {string}
     * @memberof BuildingDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTO
     */
    surface?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTO
     */
    roomsNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTO
     */
    year?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingDTO
     */
    specificCharacteristics?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BuildingDTO
     */
    floor?: number | null;
    /**
     * 
     * @type {AddressDTO}
     * @memberof BuildingDTO
     */
    address?: AddressDTO;
}

/**
 * Check if a given object implements the BuildingDTO interface.
 */
export function instanceOfBuildingDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BuildingDTOFromJSON(json: any): BuildingDTO {
    return BuildingDTOFromJSONTyped(json, false);
}

export function BuildingDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'surface': !exists(json, 'surface') ? undefined : json['surface'],
        'roomsNumber': !exists(json, 'roomsNumber') ? undefined : json['roomsNumber'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'specificCharacteristics': !exists(json, 'specificCharacteristics') ? undefined : json['specificCharacteristics'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'address': !exists(json, 'address') ? undefined : AddressDTOFromJSON(json['address']),
    };
}

export function BuildingDTOToJSON(value?: BuildingDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'surface': value.surface,
        'roomsNumber': value.roomsNumber,
        'year': value.year,
        'specificCharacteristics': value.specificCharacteristics,
        'floor': value.floor,
        'address': AddressDTOToJSON(value.address),
    };
}

