/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationDTO
     */
    content?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NotificationDTO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the NotificationDTO interface.
 */
export function instanceOfNotificationDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NotificationDTOFromJSON(json: any): NotificationDTO {
    return NotificationDTOFromJSONTyped(json, false);
}

export function NotificationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function NotificationDTOToJSON(value?: NotificationDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'content': value.content,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

