/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationAddDTO
 */
export interface NotificationAddDTO {
    /**
     * 
     * @type {string}
     * @memberof NotificationAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationAddDTO
     */
    content?: string | null;
}

/**
 * Check if a given object implements the NotificationAddDTO interface.
 */
export function instanceOfNotificationAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NotificationAddDTOFromJSON(json: any): NotificationAddDTO {
    return NotificationAddDTOFromJSONTyped(json, false);
}

export function NotificationAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function NotificationAddDTOToJSON(value?: NotificationAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
    };
}

