/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { NotificationDTO } from './NotificationDTO';
import {
    NotificationDTOFromJSON,
    NotificationDTOFromJSONTyped,
    NotificationDTOToJSON,
} from './NotificationDTO';

/**
 * 
 * @export
 * @interface NotificationDTORequestResponse
 */
export interface NotificationDTORequestResponse {
    /**
     * 
     * @type {NotificationDTO}
     * @memberof NotificationDTORequestResponse
     */
    response?: NotificationDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof NotificationDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the NotificationDTORequestResponse interface.
 */
export function instanceOfNotificationDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NotificationDTORequestResponseFromJSON(json: any): NotificationDTORequestResponse {
    return NotificationDTORequestResponseFromJSONTyped(json, false);
}

export function NotificationDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : NotificationDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function NotificationDTORequestResponseToJSON(value?: NotificationDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': NotificationDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

